#!/usr/bin/env bash
# configures new nginx server on ubuntu, creates .html, and tests it
apt-get update
apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello Holberton School this server is coooool!" > /usr/share/nginx/html/index.html
service nginx restart
