#!/usr/bin/env bash
# sets up a new nginx server on ubuntu with a redirect
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
newlines="\\\return ^/redirect_me https://www.youtube.com/watch?v=iKxAveQdtvg permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload