#!/usr/bin/env bash
# sets up a new nginx server on ubuntu with a redirect
apt-get update
apt-get -y install nginx
echo "Holberton School" | tee /usr/share/nginx/html/index.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "37i\ $redirect" /etc/nginx/sites-available/default
service nginx start