#!/usr/bin/env bash
# configs a server with HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y install 'haproxy'
cat > '/etc/haproxy/haproxy.cfg' << EOF
frontend wolfhopkins.tech
	bind *:80
	stats uri /haproxy?stats
	default_backend web_servers
backend web_servers
	balance roundrobin
	server web-01 35.196.166.174
	server web-02 34.74.134.64
EOF
service haproxy reload
service haproxy restart
