#!/usr/bin/env bash
# script displays non bad-luck number
i=1
while [ $i -le 20 ];
do
	echo "$i"

	case $i in

	     4) echo "bad luck form China";;
	     9) echo "bad luck from Japan";;
	     17) echo "bad luck from Italy";;

	esac

	(( i++ ))
done
